apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../dev

patches:
  - path: patch-frontend.yaml
  - path: patch-backend.yaml
  - path: patch-distgit.yaml
  - path: patch-keygen.yaml

