---
- name: install PostgreSQL
  package:
    name:
      - postgresql-server
      - python3-psycopg2
    state: installed

- name: Initialize PostgreSQL database if not present
  ansible.builtin.command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf

- name: Start and enable PostgreSQL service
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    enabled: true
