apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: copr

labels:
  - pairs:
      app: copr
    includeSelectors: false

resources:
  - volumes.yaml
  - configmaps.yaml
  - database.yaml
  - redis.yaml
  - pulp.yaml
  - frontend.yaml
  - backend.yaml
  - distgit.yaml
  - keygen.yaml
  - resalloc.yaml
  # builder.yaml is a template for dynamic provisioning, not deployed directly

